#62 Models.Advert
PGBSNH19/project-g2 pull request #14
Opened 2020-12-16 14:21 UTC by AntonNorgren

Created Advert.cs.
Added properties for class.

2020-12-16 14:42 UTC, Gerglamesh approved these changes
👍

2020-12-16 14:45 UTC, AndreasBrochs approved these changes
Maybe Content should be Body? But looks good.

2020-12-16 14:52 UTC, BenYtt requested changes

2020-12-16 14:52 UTC, BenYtt commented on KNet/KNet.API/Models/Advert.cs
> +        public int UserId { get; set; }
Should be a guid no?

2020-12-17 08:10 UTC, BenYtt approved these changes

2020-12-17 08:11 UTC, merged